services:
  landing-page:
    container_name: landing-page
    restart: unless-stopped
    build: .
    ports:
      - "8082:8082"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`tailtag.link`)"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=8082"

networks:
  traefik:
    name: traefik
    external: true
